### ISSUE TITLE
"default" key not allowed in config files?

### ISSUE THREAD

**Issue by olivierphi** [chatgris/Gaston#5]
Hello,

I've added a config setting in a YAML Gaston file this morning, and I now have an error with this setting because its key name is "default".

I have not been able to see anything related to this in the Gaston source code, so it may not be a Gaston problem, but I can't understand this behaviour :-/

Sample file :

``` yaml
# config/gaston/test.yml
:gaston:
  setting:
    default: test
    other_key: test2
```

Warn message  with this file: 
**default method already exists on Gaston::GastonSetting, value: test**
_(seems to come from Gaston::Builder)_
Furthermore, the "Gaston.setting" hash doesn't have the "default" key :

```
>> Gaston.setting
{"other_key"=>"test2"}
```
